version: 2.1
orbs:
    node: circleci/node@2.1.0
jobs:
  deploy:
  environment:
      IMAGE_NAME: scaaz/serverandclient
  docker:
    - image: circleci/buildpack-deps:stretch
  steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build Docker image
            command: cd server && docker build -t $IMAGE_NAME:serverobraz 
        - run:
            name: Publish Docker Image to Docker Hub
            command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:serverobraz
        - run:
            name: Build Docker image
            command: cd client && docker build -t $IMAGE_NAME:clientobraz
        - run:
            name: Publish Docker Image to Docker Hub
            command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:clientobraz
  			
    build-and-test-client:
        executor: 
          name: node/default
        steps:
            - checkout
            - run: cd client && npm install
            - run: cd client && npm test
    build-and-test-server:
        executor: 
          name: node/default
        steps:
            - checkout
            - run: cd server && npm install
            - run: cd server && npm test
workflows:
    build-and-test:
        jobs:
        - build-and-test-client
        - build-and-test-server
        deploy:
          jobs:
            -deploy
